defaults: &defaults
  redis_url: 'redis://127.0.0.1:6379/0'
  redis_namespace:
  webhook_url:
    iadmin: 'https://hooks.slack.com/services/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'
    archeage: 'https://hooks.slack.com/services/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'
    lodoss: 'https://hooks.slack.com/services/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'
    oiax: 'https://hooks.slack.com/services/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'
  mongo_uri: 'localhost:27017'
  cache_server:
    - 'localhost:11211'

development:
  <<: *defaults

test:
  <<: *defaults
  redis_url: 'redis://127.0.0.1:6379/1'

staging:
  <<: *defaults

production:
  <<: *defaults
  redis_url: 'redis://127.0.0.1:6379/2'
  cache_server:
    - 'memcached-1.pmang.jp:11211'
    - 'memcached-2.pmang.jp:11211'

role:
  staff:        <%= '00000001'.to_i(2) %>
  part_leader:  <%= '00000011'.to_i(2) %>
  team_leader:  <%= '00000111'.to_i(2) %>
  group_leader: <%= '00001111'.to_i(2) %>
  manager:      <%= '00011111'.to_i(2) %>
  director:     <%= '00111111'.to_i(2) %>

permission:
  staff:        <%= 1 << 0 %>
  part_leader:  <%= 1 << 1 %>
  team_leader:  <%= 1 << 2 %>
  group_leader: <%= 1 << 3 %>
  manager:      <%= 1 << 4 %>
  director:     <%= 1 << 5 %>
